### ISSUE TITLE
export ritten leeg ?

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#103]
export ritten als eigenaar lukt maar de xls bevat enkel de titelrij.

**Comment by kcoolsae** [comment]
Rapporten werken nog niet. De code moet nog flink worden opgekuist, maar zal dan ook bruikbaar zijn voor heel wat meer rapporten dan er nu zijn.

Ik wist zelfs niet dat het nog mogelijk was rapporten op te vragen. Ik schakel dit voorlopig uit.
