### ISSUE TITLE
commentaarveld auto

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#109]
In het commentaarveld van een auto kan er nu geen html worden ingegeven.
Of Enter ofzo.
Zou wel handig zijn.

**Comment by kcoolsae** [comment]
Note to self: gebruik PegDown om dit op te lossen. (Geen HTML maar markdown.)

**Comment by genoot** [comment]
markdown wordt ook gebruikt bij aankondigingen

**Comment by genoot** [comment]
weergave van opmaakcodes in autolijst nog niet optimaal
`
> <p><strong>automaat</strong> - en <em>hybride</em> (voorzie 10 minuten uitleg bij de eerste keer) - containerparkbezoek graag melden</p> <p>Bushalte op 300m (Banierpark) - bussen 3, 6, 34-35-36, 76-77</p>`

**Comment by genoot** [comment]
> <p><strong>automaat</strong> - en <em>hybride</em> (voorzie 10 minuten uitleg bij de eerste keer) - containerparkbezoek graag melden</p> <p>Bushalte op 300m (Banierpark) - bussen 3, 6, 34-35-36, 76-77</p>

**Comment by genoot** [comment]
<p><strong>automaat</strong> - en <em>hybride</em> (voorzie 10 minuten uitleg bij de eerste keer) - containerparkbezoek graag melden</p> <p>Bushalte op 300m (Banierpark) - bussen 3, 6, 34-35-36, 76-77</p>

**Comment by genoot** [comment]
hier wel natuurlijk ;-)
