### ISSUE TITLE
tankbeurt foute en ontbrekende waarde

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#112]
bij de tankbeurt wordt nu wel 20,15 aanvaard maar 20 niet

nu werken we als controlemiddel ook met (verplicht in te geven)
aantal liter
kilometerstand bij tanken

kunnen hiervoor nog extra velden opgenomen worden ?

**Comment by kcoolsae** [comment]
Tweede issue (extra velden) overgezet naar #114

Wat ingeven van bedragen betreft: de komma (of punt) bij bedragen in euro was bedoeld als extra veiligheid, maar ik heb zelf ook al gemeld dat ik dat vervelend vond, dus ik pas dat wel aan.
