### ISSUE TITLE
details leden zichtbaar

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#116]
details v leden zijn nog zichtbaar voor iedereen
vb
http://scespi.ugent.be/degapp/profile/byid?userId=5

**Comment by kcoolsae** [comment]
Kan je wat specifieker zijn en vastleggen wie deze details wel mag zien?

**Comment by genoot** [comment]
enkel admin mag dit zien.
eigenaar mag zien indien de ontlener de auto reserveerde.
ontlener mag zien wie voor- of na hem komt.

vooral vermijden dat iemand (met script) ledeninfo kan binnenhalen

**Comment by kcoolsae** [comment]
Overgeplaatst naar #164
