### ISSUE TITLE
gemiddeld aantal km - leeg maken

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#117]
bij "aantal km/jaar" is nu de waarde van de auto vermeld
dat veld mag leeg zijn

vb klorofil: Gemiddeld aantal kilometers (per jaar): 13500

**Comment by kcoolsae** [comment]
Toont ondertussen aantal km/jaar zoals zou moeten, maar dit zal in de meeste gevallen leeg zijn want die gegevens zaten niet in de initiële upload.
