### ISSUE TITLE
bericht goedkeuring reservatie vermeldt de auto niet

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#120]
bevat niet de naam van de auto, enkel de standplaats.

We bekijken nog intern welke info we in deze mail willen meegeven.
De ontlener zal nu effectief met de auto rijden en mag misschien wat meer details weten over de auto, of extra info om een goede sleutelafspraak te maken.
Deze info kan per auto verschillend zijn.

**Comment by kcoolsae** [comment]
Auto nu wel vermeld.

Issue blijft open in afwachting van wat er nog meer in de mail moet komen. Dit afhankelijk maken van de auto, zal niet evident zijn. Dus: liever niet.

**Comment by genoot** [comment]
Er is niet echt vraag naar die extra info.
