### ISSUE TITLE
bewijzen en profielfoto's afschermen

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#132]
bewijzen en profielfoto's staan open voor iedereen die ingelogd is ?
vb ... refuels/proof?proofId=4
kan dit beter afgeschermd ? 

bvb profielfoto enkel zichtbaar als je op profiel lid kijkt 
of, tankbewijs / autokost enkel zichtbaar voor wie het aanbelangt ?

**Comment by kcoolsae** [comment]
Zichtbaarheid voor profielfoto zal dezelfde moeten zijn als voor het profiel zelf. Dus enkel toegankelijk maken op de profielpagina lukt niet gemakkelijk.

Zichtbaarheid tankbewijs / autokost aanpassen is wel te doen

**Comment by kcoolsae** [comment]
Al gedeeltelijk opgelost: je kan niet meer een tankbewijs opvragen waar een profielfoto verwacht wordt e.d., 

Permissies moeten nog worden nagekeken
