### ISSUE TITLE
wachtwoord vergeten foutmelding

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#133]
als Melanie haar wachtwoord wil wijzigen komt de melding dat het email adres fout is (niet identiek als het geregistreerde) het is echter wel juist

na klik ok lukt het wel om verder te gaan, nieuw wachtwoord is ook actief

ps typo : 'vergetem' ipv 'vergeten'

**Comment by kcoolsae** [comment]
Uit de log blijkt dat dezelfde actie twee keer snel achter elkaar is doorgegeven (0.3 seconden tussen beide). Misschien per ongeluk dubbelgeklikt (maar de browser zou daarover moeten reclameren)?

De eerste keer is geslaagd, maar de tweede keer gaf een fout.

Voorlopig sluit ik dit, wellicht was dit een toevalstreffer.
