### ISSUE TITLE
tankbeurt ingeven

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#134]
tankbeurt ingeven met kommagetal gaat niet zowel met , als met .
als ik dan een cijfer ingeef kreeg ik foutmelding : 6l3e634bb

**Comment by kcoolsae** [comment]
De foutmelding lijkt er eerder op te wijzen dat er geen bonnetje was. Is dat mogelijk?

(Je kan geen tankbeurt ingeven zonder meteen ook een bonnetje te uploaden.)

In ieder geval moeten de foutmeldingen hier wat beter.
