### ISSUE TITLE
berichten en antwoorden bij elkaar

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#136]
Kunnen bij de berichten het eigen bericht en het antwoord onder elkaar komen ?
Nu gaat de conversatie verloren.

**Comment by kcoolsae** [comment]
Bovenstaande is niet zo evident te implementeren. Het is ook niet de bedoeling dat we hier een parallel e-mailsysteem opzetten.

Berichten met een zeker ouderdom automatisch verwijderen?
