### ISSUE TITLE
einde reservatie na begin

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#137]
einde reservatie komt best default na begintijdsstip van die reservatie.
nu is dat nog het huidige tijdsstip (was dit niet al eerder opgelost ?)

**Comment by kcoolsae** [comment]
Ik dacht inderdaad dat dit al was opgelost.
Kun je me zeggen op welk 'scherm' je dit hebt gezien?

**Comment by genoot** [comment]
klikken op een vrij blokje in het reservatieschema om begin v reservatie te kiezen, dan is het voorgestelde eindmoment steeds het huidige tijdsstip (en dus vroeger dan het toekomstige beginpunt)
