### ISSUE TITLE
paswoord niet altijd herkend - cokies ?

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#140]
af en toe wordt ww niet herkend na uit/inloggen.
paswoord is enkele keren gereset als test.
daarna af en toe een probleem

**Comment by kcoolsae** [comment]
Sorry, ik zie niets eigenaardigs in de logs en ik kan dit niet reproduceren.

Als je een serie handelingen kunt opgeven waarbij de fout gegarandeerd optreedt, mag je de issue opnieuw heropenen.
