### ISSUE TITLE
foutmelding gemeld door gebruiker stefanie de puit

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#141]
Ritten > gepland > details : Oops, an error occured. This exception has been logged with id 6l4mn0fp1.

**Comment by kcoolsae** [comment]
On 02/05/2015 02:19 PM, Lootens wrote:
> Ritten > gepland > details : Oops, an error occured. This exception has
> been logged with id 6l4mn0fp1.

2 seconden geleden opgelost!

-- 
________________________________________________________________________

Kris Coolsaet                       e-mail:   Kris.Coolsaet@UGent.be
tel. +32 (0)9 264 4889              home:     http://twizz.UGent.be/~kc/
________________________________________________________________________
Let others boast of martial dash, for we have boldly fought with cash
                     -- Ankh-Morpork National Anthem [Terry Pratchett]

**Comment by Lootens** [comment]
WAT EEN SERVICE !

gr
Karel.
