### ISSUE TITLE
blokje blijft rood gekleurd na annulering

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#144]
blokje blijft rood gekleurd (bezet) van een reservatie die is geannuleerd.

**Comment by kcoolsae** [comment]
Ik heb één geval nagegaan (BlueLagoon 1/1/2015 07:00-16:30), en daar lijkt er een tweede reservatie te bestaan op hetzelfde moment. Dus het rood mag blijven in dat geval.

Als er andere gevallen zijn waar er geen valide overlappende reservatie is, graag details daarover.

Ik probeer een lijst te maken van overlappende reservaties in de huidige database, maar dat is niet evident.

**Comment by genoot** [comment]
klorofil 5 feb NM
klorofil 7 feb 8u-8u30
geannuleerde reservaties staan nog op het schema.
auto lijkt bezet maar is eigenlijk vrij.
