### ISSUE TITLE
eigenaar wil begonnen rit verwijderen

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#154]
eigenaar moet begonnen rit -die niet doorgaat- kunnen verwijderen.

voorstel: 2 opties voorzien
* rit annuleren
* niet opgedaagd (rit wordt ook geannuleerd, maar de "niet-opdagers" zijn problematisch moeten uit rapportage kunnen gehaald worden, en eventueel "getarifieerd")

**Comment by kcoolsae** [comment]
Voorlopig voorzie ik enkel een annulatie die echter wel speciaal gemarkeerd wordt als 'rit is niet doorgegaan'.

Is het wel een goed idee om de eigenaar zelf te laten kiezen tussen twee verschillende vormen van annulatie? Zolang de rit niet is begonnen kunnen trouwens zowel eigenaar als ontlener de rit nog annuleren.

**Comment by genoot** [comment]
eigenaar is best geplaatst om onderscheid te maken tss propere annulatie of "niet opdagen".
voor opvolging van problemen is dit belangrijk.

eigenaar kan nu geen goedgekeurde aanvraag annuleren, toch ?
enkel admin
da's ook de bedoeling.
