### ISSUE TITLE
toon overzicht auto's

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#155]
overzicht van de autolijst wordt gemist.

voorstel : 
een blauw knopje "overzicht auto's" toevoegen om een lijst te tonen:
* lijst bevat met auto-info, zoveel mogelijk adhv tags ; verder minimaal open commentaar
* lijst bevat ook adres, maar geen mail of telnr vd eigenaar.

een klik op 1 auto verwijst naar de volledige auto-fiche

blauwe balkjes blijven best zichtbaar, zodat men van hieruit snel een reservatie kan maken.

**Comment by kcoolsae** [comment]
Voorlopig in beraad...

**Comment by genoot** [comment]
het overzicht dat wordt gemist is de info die nu per auto is te zien als je op de auto klikt vanuit het dagoverzicht.
om geen 32x te moeten klikken is een overzicht handig.
vanuit dat overzicht zou men graag een auto kunnen kiezen en verdergaan naar de plek waar die gereserveerd kan worden.
