### ISSUE TITLE
mail bij activatie lidmaatschap

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#160]
bij activatie van het lidmaatschap en toekennen van lidnummer van een persoon mag degapp een mail sturen met de melding dat het delen kan beginnen. 
voorstel template komt via mail

de mail hoeft enkel gestuurd bij toekenning lidmaatschap, niet als de persoon gedeblokkeerd wordt

**Comment by kcoolsae** [comment]
De bug zelf is gemakkelijk op te lossen. De oorzaak van de bug ligt bij het feit dat er twee verschillende manieren zijn om een gebruiker 'full user' te maken: 
* de /normale/ weg, via de lijst goedkeuring gebruikers
* rechtstreeks via het profiel
Dit laatste is geen goede manier om te werken, omdat er dan bijvoorbeeld geen contractverantwoordelijke kan opgegeven worden. 

Dit gedeelte van de bug is overgeheveld naar #163.
