### ISSUE TITLE
tankbeurt formaat bedrag

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#184]
als bedrag voor de tankbeurt wordt enkel aanvaard : 0,00
bvb 36,9 is niet voldoende; je moet 36,90 invullen 
dat is streng.

**Comment by kcoolsae** [comment]
Ik vond het niet slecht om streng te zijn bij het ingeven van bedragen, maar OK, bij algemene aanvraag zal ik dit aanpassen: Tenslotte worden de bedragen achteraf ook nog eens nagekeken door een administrator

Dit wordt: 1 of 2 cijfers na de komma zijn toegelaten. Ook *geen* komma is toegelaten. (Decimale) punten zijn niet toegelaten, en als er een komma staat dan ook minstens één cijfer.
