### ISSUE TITLE
ontlener moet zelf ritten kunnen invullen in het verleden

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#196]
hoi,

Gerbrand had dit getest en dit lukte (maar hij is wel eigenaar). Vandaag wordt opgemerkt dat dit toch niet kan.

Zou je dit kunnen toelaten Kris ?

Melding nu is : Een reservatie uit het verleden kan enkel door de eigenaar worden ingebracht
maar doel is dat de ontlener het werk doet ...

groet
Karel.

**Comment by kcoolsae** [comment]
DIt is technisch mogelijk, maar ik vind dit geen goed idee. Het haalt de ganse workflow overhoop,

In principe zou deze situatie zich niet mogen voordoen: het betekent dat een rit is gereden zonder dat die eerst werd gereserveerd. Voor de eigenaar kan ik me dit nog een beetje indenken, maar voor een gewone ontlener zou dit niet mogen gebeuren: dit betekent dat eigenaar en ontlener iets hebben geregeld buiten het systeem om, en dat is niet de bedoeling.

Als ik dit implementeer zou ik er sowieso willen voor kiezen om enkel de reservatie toe te laten. De eigenaar zal die nog altijd a posteriori moeten goedkeuren.

Graag commentaar

**Comment by Lootens** [comment]
Dag Kris,

Zonet met Gerbrand dit wat besproken en we volgen je zowaar ...
Het doel is en blijft altijd de rit op boeken en niet achteraf alles regelen.
Zeker in deze fase zien we toch nog wat bijstuur werk op dit vlak.
Concreet voor nu dus laten invullen door de eigenaar (ook in het verleden en nieuw is dus dat hij daar een ontlener moet kiezen)
voor ons hoeft hiervoor geen communicatie naar de ontlener hierover

groet
Karel.
