### ISSUE TITLE
Posities van auto's zichtbaar op een kaartje

### ISSUE THREAD

**Issue by kcoolsae** [kcoolsae/Degage#2]
De standplaatsen van de auto's zouden ergens moeten terug te vinden zijn op een kaartje.

(Dit was zo in de oorspronkelijke versie van Zelensis, maar was slordig geprogrammeerd. Dit moet opnieuw bekeken worden.)

**Comment by genoot** [comment]
voorlopig wordt er met dit kaartje gewerkt (manuele updates)
http://www.degage.be/autodelen/deelauto/
