### ISSUE TITLE
ingevoerde kosten sorteren

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#204]
Suggestie van een eigenaar om in het overzicht van de autokosten te sorteren op datum van de kost.

**Comment by kcoolsae** [comment]
Het overzicht wordt nu gesorteerd op datum van de kost, meest recente kost bovenaan. 
In de toekomst moeten we misschien afzonderlijke kolommen sorteerbaar maken, maar voorlopig is dit technisch alleen mogelijk op 'gepagineerde' tabellen
