### ISSUE TITLE
Voorzie UI voor BTW-nummer

### ISSUE THREAD

**Issue by kcoolsae** [kcoolsae/Degage#206]
Het (eventuele) BTW-nummer van een gebruiker is reeds opgenomen in de databank maar er is nog geen user interface voorzien om dit ook in te geven via de webapplicatie.

**Comment by genoot** [comment]
tekstvermelding : BTW-nummer voor vermelding op je afrekening

**Comment by genoot** [comment]
Aangemaakt maar onzichtbaar gezet wegens niet vereist.
