### ISSUE TITLE
ritdetails ingeven niet foutloos

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#21]
* ingegeven kmstand wordt de eerste keer telkens genegeerd - komt telkens op 0. Pas bij wijzigen wordt het aanvaard.
* ingave kmstand moet vorige kmstand suggereren als beginkmstand van de rit 
(aanpassen moet mogelijk blijven ingeval er iemand zijn rit nog niet heeft ingevuld)
* controle kmstand zodat er geen overlap is of kmstanden die niet kunnen kloppen
(als auto vandaag kmstand 30000 heeft, mag er geen rit op vorige week genoteerd worden met kmstand 20000)
* reservatieperiode vd rit moet aangepast kunnen worden
* tankbeurt : bedrag en hoeveelheid moet later nog aangepast kunnen worden. Hoeveelheid en kmstand bij tankbeurt moet ook optioneel kunnen ingegeven worden

**Comment by kcoolsae** [comment]
Meeste opgelost of niet relevant meer wegens verandering van interface
