### ISSUE TITLE
lijst gebruikers opsplitsen

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#228]
Kan de lijst gebruikers meerdere tabbladen krijgen ?
Dat lijkt beter voor een correct overzicht.

leden
kandidaatleden
ex-leden
geblokkeerde leden

**Comment by genoot** [comment]
toevoegen datumvelden + sortering

**Comment by eisebaert** [comment]
uit mail:

_dag Emmanuel,

Werkt prima.
Ik heb nog wat verbetersuggesties.

* Tussen "Lidmaatschap aangevraagd" en "Geregistreerd" hangt er nog een groep die naar een infosessie is geweest maar nog geen aanvraag indiende om lid te worden.
Die volgen we graag op en zouden best ook apart getoond worden.

* Per categorie zou ik het relevante datumveld vermelden :
- leden : start lidmaatschap (ok dus)
- lidm aangevraagd : indiendatum
- geregistreerd : registratiedatum 
- geinformeerd : datum infosessie
- geblokkeerd : datum blokkering (denk niet dat we die nu hebben)
- verwijderd : datum verwijdering (denk niet dat we die nu hebben)

* sortering :
elke categorie zou ik default op datum sorteren : recentste bovenaan


Het is gelinkt aan een beter gebruikersbeheer, waarvoor enkele extra velden nodig zijn
- datum stopzetting
- reden stopzetting / schrapping / blokkering

Iemand "verwijderen/schrappen" moet dan ook mogelijk worden met een beheerdersknop. Of komen als keuze achter de knop "Gebruikersstatus wijzigen".

groet,
Gerbrand_

**Comment by eisebaert** [comment]
wel opgemerkt dat zoeken van een lid de eerste keer niet werkt.
pas nadat je op een andere categorie hebt geklikt en dan terugkeert naar de categorie waar je wil zoeken, werkt het.

**Comment by genoot** [comment]
enkele zaken blijven nog open:
- vermelding relevante datumveld naargelang categorie
- default sortering
- ontbrekende categorie
- extra velden
- Iemand "verwijderen/schrappen"
