### ISSUE TITLE
parkeerkaarten overzicht

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#256]
Info parkeerkaarten dient toegevoegd aan autofiche.

**Comment by eisebaert** [comment]
uit mail:

hoi,

Net als pechverhelping zouden we ook de gegevens van de parkeerkaarten (vb in bijlage) willen bijhouden en tonen in een overzicht. Ik heb issue #256 hiervoor aangemaakt.
Hieronder wat uitleg.

Bij de autofiche zijn deze extra velden nodig onder de noemer "parkeerkaart"
- stad/gemeente (tekst)
- parkeerzones (tekst)
- vervaldatum (datum)
- nummer (tekst)

In een overzicht voor de beheerder dient ook de autonaam en de nummerplaat getoond.

Een ontlener zou voor de reservatie moeten kunnen zien of de deelauto over een geldige parkeerkaart beschikt.

groeten,
Gerbrand

**Comment by eisebaert** [comment]
brief van parkeerbedrijf:

 Liselotte Hardy Voorhavenlaan 50 9000 Gent
Activatie parkeervergunning autodelen met nummer 103594
Beste
datum: 18‐11‐2016
De parkeervergunning autodelen met vergunningnummer 103594, gekoppeld aan de wagen met nummerplaat 1RCF615, is geactiveerd. De vergunning loopt van 18‐11‐2016 tot 17‐11‐2017.
U kunt met uw vergunning parkeren op alle reglementaire parkeerplaatsen van het Gentse grondgebied waar een parkeerregime van kracht is.
U bent uiteraard steeds welkom aan de balie van het Mobiliteitsbedrijf tijdens onze openingsuren: op maandag, dinsdag, woensdag en vrijdag van 09 tot 12u30, bijkomend op woensdagnamiddag van 14 tot 16u. Dinsdagavond enkel op afspraak van 16u30 u tot 19u. Op donderdag zijn de loketten gesloten.
Indien uw adres wijzigt, dient u onmiddellijk contact op te nemen met het Mobiliteitsbedrijf.
Met vriendelijke groeten
Frank Vanden Bulcke Directeur Mobiliteitsbedrijf
Parkeervergunning autodelen

**Comment by genoot** [comment]
Sortering loopt nog niet goed voor deze velden:
- nummerplaat (mag als 2de kolom staan)
- stad/gemeente
- zones

Default volgorde mag car_id zijn (recentste bovenaan)
