### ISSUE TITLE
checken kmstand

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#52]
kmstand moet steeds volgen op een vorige dus hier moeten nog checks op komen.
* een rit moet niet meteen aansluiten op een vorige rit; het kan dat iemand zijn kmstand pas later ingeeft -> systeem moet dan wel aangeven dat er nog niet ingevulde kmstanden zijn (in het beste geval is hier wel een reservatie gebeurd, in het andere geval ontbreekt er gewoon een rit/reservatie/kmstand)
* een rit mag geen lagere kmstand hebben dan een eerdere rit; dat kan nu nog wel

**Comment by kcoolsae** [comment]
Kilometerstand zal gesuggereerd worden aan de hand van de kilometerstanden van de vorige en de volgende ritten voor zover ze al zijn ingegeven.

Zie ook #21
