### ISSUE TITLE
tankbeurt ingeven

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#53]
- als ik laat weten dat ik getankt hebt komt geen vraag om bonnetje op te laden
- als ik schade ingeef komt eveneens geen vraag naar detail, schermen/formulieren waren hiervoor wel voorzien dacht ik

**Comment by kcoolsae** [comment]
UI Tankbeurten is veranderd.

Schade moet afzonderlijk worden ingegeven, kan niet meteen (er zijn te veel onderdelen)
