### ISSUE TITLE
controle dubbels

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#56]
nieuwe gebruiker, controle email adres bij registratie of als je de account aanvraagt (de koppeling met inschrijven voor een sessie zit er nu niet meer in)
nu verloopt die controle pas als je je inschrijft na klik op de email link

**Comment by kcoolsae** [comment]
Dit is met opzet. Op die manier kunnen hackers niet gemakkelijk mogelijke userids/email-adressen uitproberen.
