### ISSUE TITLE
uur ‘tot’ moet groter zijn dan ‘van’ (datum controle is wel oké, uur niet)

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#58]

**Comment by genoot** [comment]
datum controle lijkt ook niet okee als ik ga via 
1. reserveer een specifieke auto
3. overzicht v reservaties voor een bep dag

vb : als ik vandaag (19/1) reserveer voor 20/1, wordt 19/1 als einddag voorgesteld
