### ISSUE TITLE
ritdetails ingeven mag opvallen

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#69]
ritten : bij tabblad "voorbij" staat er bijkomend (7) 
ik denk dat dit de ritten zijn waarvan ritdetails nog ingevuld moeten worden.
die ritten vallen te weinig op in het lijstje.

sorteren van de ritten door klik op kolomtitel lukt nog niet.
edoch, als ik klik op "Van" krijg ik de melding "er ging iets mis"

**Comment by kcoolsae** [comment]
De melding 'er ging iets mis' is ondertussen OK.

Doorheen de ganse applicatie zijn er nog heel wat kolommen waarop zou gesorteerd kunnen worden. Dit wordt in een later stadium aangepast. (Overgedragen naar #71.)

De knop 'ritdetails invullen' krijgt een ander kleurtje.

**Comment by genoot** [comment]
>> De knop 'ritdetails invullen' krijgt een ander kleurtje.

Kleurtje mag ook voor de ritten van een eigenaar - die vallen te weinig op
