### ISSUE TITLE
Sorteren en filteren van tabellen

### ISSUE THREAD

**Issue by kcoolsae** [kcoolsae/Degage#71]
Er zijn heel wat tabellen waarbij het nuttig zou zijn om te kunnen klikken op bepaalde kolommen om ze te kunnen sorteren en eventueel ook nog achteraf filteren op kolominhoud. 

Heel wat van die functionaliteit is in het programma reeds voorzien. Ze moet alleen nog hier en daar toegepast worden (en opgepoetst).

**Comment by genoot** [comment]
als eigenaar 
-  sorteren tankbeurten op datum / op bedrag
-  sorteren ritten op ontlener

als beheerder
- sorteren autokosten op auto / datum / type kost
- gebruiker op datum start lidmaatschap / op status
- auto's op status / bouwjaar (nu niet getoond)
