### ISSUE TITLE
html tag's te zien bij notificaties

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#77]
in mijn zonet nieuw ontvangen bericht (online in chrome) over mijn aanmelding als eigenaar zijn de html tags nog te zien (<p> en <br>)

**Comment by kcoolsae** [comment]
Kan dit niet reproduceren. Misschien vanzelf opgelost door een andere issue op te lossen?

**Comment by genoot** [comment]
bij het knopje "mededelingen" rechtsboven is de html code nog te zien
