### ISSUE TITLE
verfijnen lijst gebruikers

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#8]
wie de lijst van gebruikers opvraagt, ziet iedereen die is geregistreerd, ook wie nog geen lid is.

kunnen we hier filteren ofwel markeren naargelang status 
* ontlener
* eigenaar
* kandidaat wacht op infosessie
* kandidaat geweest naar infosessie 
* kandidaat wacht op contract
* ex-ontlener
* ex-eigenaar
...

**Comment by kcoolsae** [comment]
Dit lijkt opgelost. Er zijn geen ex-gebruikers maar gebruikers kunnen wel geblokkeerd worden
