### ISSUE TITLE
auto aanmaken

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#80]
tijdens het aanmaken van een auto kreeg ik volgende foutmelding
6l0jgiiob

ik vulde alle veldjes in

daarna wel gelukt door enkel de minimale velden in te vullen
fout proberen nabootsen, ik vermoed dat het komt omdat ik deuren en zitplaatsen zelf invul ipv te werken met de pijltjestoetsen (foutmelding 6l0jh3i9a)

**Comment by kcoolsae** [comment]
Kan dit niet reproduceren (en de foutmeldingen zijn verdwenen)

**Comment by kcoolsae** [comment]
Heb iets gevonden in de backups van de logfiles:

Eerste fout:

    Failed to create new car. -- Cannot convert class be.ugent.degage.db.models.File to SQL type 
    requested due to java.lang.ClassCastException - be.ugent.degage.db.models.File cannot be cast to 
    java.lang.Number
    at be.ugent.degage.db.jdbc.JDBCCarDAO.createCar(JDBCCarDAO.java:272)

Tweede fout:

     Failed to create new car. -- Duplicate entry '' for key 'ix_details'
     at controllers.Cars.addNewCar(Cars.java:334)

**Comment by Lootens** [comment]
nog eens getest in de productieomgeving en daar kreeg ik 
6l2j36c8c als foutmelding
alles ingevuld wat nodig is (via pijltjes ook de cijfers ingevuld)
