### ISSUE TITLE
berichten sturen als kandidaat-lid

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#82]
iemand die zich net heeft geregistreerd, kan ook al berichten sturen naar leden.
en daarmee ook de ledenlijst doorbladeren.
kan dat voorbehouden worden voor actieve leden ?

**Comment by kcoolsae** [comment]
Mag helemaal geen berichten kunnen sturen

**Comment by kcoolsae** [comment]
Wordt verder afgehandeld in #89
