### ISSUE TITLE
auto eigenaar ziet zijn eigen wagen niet

### ISSUE THREAD

**Issue by Lootens** [kcoolsae/Degage#83]
kanarie als admin aangemaakt en gekoppeld aan eigenaar user id9
maar voor user niet te zien (user = karel.lootens@gmail.com familienaam 'eigenaar')

of maak ik een fout als admin ?

**Comment by genoot** [comment]
eigenaar is niet automatisch een user, zag ik daarnet.
dus als ontlener toevoegen

**Comment by Lootens** [comment]
Gerbrand ik zag niet meteen waar ik eigenaar karel ook kan toevoegen als ontlener

waar vind ik dit terug?
gr
k.

**Comment by genoot** [comment]
als superuser zie je links onderaan "gebruikersrollen".
dan klik je op de juiste persoon en voeg je een rol "gebruiker" toe

**Comment by kcoolsae** [comment]
Zelfde als #86
