### ISSUE TITLE
eigen auto op dashboard

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#85]
een eigenaar mag de eigen auto op het dashboard zien.

bij reservaties zal hij meestal de eigen auto nemen
en een eigenaar wil ook snel het overzicht van de reservaties van de eigen auto zien.

kan dat ?

**Comment by kcoolsae** [comment]
De grote knoppen voor "ongelezen berichten" en "volledigheid profiel" mogen weg omdat die ook al rechts bovenaan staan.

**Comment by kcoolsae** [comment]
Vraagje: mogen die twee knoppen ook weg bij de gewone gebruiker (niet-eigenaar?) In dat geval
blijft er nog enkel de grote 'ritten'-knop over. Als alternatief zou ik dan eventueel het rittenoverzicht op de welkomstpagina kunnen zetten, ook bij een niet-eigenaar.

**Comment by genoot** [comment]
ja, knoppen mogen weg.

gebruiker mag op het dashboard zeker "eigen rittenoverzicht" zien

ook handig dan weer zijn "informatieve systeemberichten" die niet moeten gepusht worden naar de gebruiker (vb: "auto Blackbird is als deelauto gestart op 1 januari aan de Brugse Poort");
of ben ik hier ook vergeten wat eerder gezegd is ?

**Comment by kcoolsae** [comment]
Tweede deel (informatieve systeemberichten) afgesplitst naar #115 want niet haalbaar voor deze milestone.

Verandering van dashboard van gewone gebruiker blijft in milestone.
