### ISSUE TITLE
lijst ontvangers berichten wijzigen

### ISSUE THREAD

**Issue by genoot** [kcoolsae/Degage#89]
ontleners mogen geen berichten naar elkaar sturen, wel naar de auto's.

lijst van mailadressen dient aangepast.

**Comment by kcoolsae** [comment]
Wie mag berichten sturen naar wie?

Ik was al zover:
- Niet-leden mogen geen berichten sturen
- Leden mogen berichten sturen naar auto's (= auto-eigenaars)
- Iedereen mag een reply doen op een bericht dat hij heeft ontvangen

Maar:
- Mogen auto-eigenaars naar iedereen een bericht sturen?
- En mogen admins naar iedereen een bericht sturen?

Graag uitsluitsel hierover.

**Comment by kcoolsae** [comment]
De situatie is nu als volgt:

* Niet-leden mogen geen berichten sturen
* Leden mogen berichten sturen naar auto-eigenaars
* Iedereen mag een reply doen
* Auto-eigenaars en admins kunnen naar iedereen sturen
